:: Note: -DINVOKE_LITE_OPT_SELECT_NONSTD=ON is non-functional
cmake -S . -B build -G Ninja -DCMAKE_CXX_STANDARD=11 -Dinvoke_USE_ALTERNATE_IMPL=1 -DCMAKE_BUILD_TYPE=Release -DINVOKE_LITE_OPT_SELECT_NONSTD=ON -DINVOKE_LITE_OPT_BUILD_TESTS=ON -DINVOKE_LITE_OPT_BUILD_EXAMPLES=ON
cmake --build build --config Release

